name: Build JSON Schema

on:
    push:
        branches:
            - 'main'
    pull_request:
        branches:
            - 'main'

jobs:
    build:
        name: Build JSON Schema
        runs-on: ubuntu-latest
        steps:
            - name: Check out the code
              uses: actions/checkout@v4
              with:
                fetch-depth: 1
            
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.12.4'

            - name: Install Poetry
              uses: abatilo/actions-poetry@v3
              with: 
                poetry-version: '1.8.3'
            
            - name: Setup a local virtual environment (if no poetry.toml file)
              run: |
                poetry config virtualenvs.in-project true
                poetry config virtualenvs.in-project true --local
            
            - uses: actions/cache@v4
              name: Cache Poetry virtualenv
              with:
                path: ./.venv
                key: venv-${{ hashFiles('poetry.lock') }}

            - name: Install dependencies
              run: python -m poetry install  
            
            - name: Build JSON Schema
              run: |
                poetry run python configschema/main.py
            - name: Upload JSON Schema to Artifacts
              uses: actions/upload-artifact@v4
              with:
                name: configschemaJson
                path: dist/configschema.json