name: Build JSON Schema

on:
    push:
        branches:
            - 'main'
    pull_request:
        branches:
            - 'main'

jobs:
    build:
        name: Build JSON Schema
        runs-on: ubuntu-latest
        steps:
            - name: Check out the code
              uses: actions/checkout@v4
              with:
                fetch-depth: 1
            
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.12.4'

            - name: Install dependencies
              run: |
                python -m poetry install      
            - name: Build JSON Schema
              run: |
                poetry run python configschema/main.py
            - name: Upload JSON Schema to Artifacts
              uses: actions/upload-artifact@v3
              with:
                name: configschemaJson
                path: dist/configschema.json